server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alicyu1024/microservicecloud-config.git #GitHub上面的git仓库名字
          # uri: git@github.com:Alicyu1024/microservicecloud-config.git git方式不行,需要使用https方式