package com.test.entity;

import java.io.Serializable;

public class Books implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Publishingdate
     *
     * @mbg.generated
     */
    private String publishingdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Salesamount
     *
     * @mbg.generated
     */
    private Integer salesamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.Storenumber
     *
     * @mbg.generated
     */
    private Integer storenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table books
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Id
     *
     * @return the value of books.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Id
     *
     * @param id the value for books.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Author
     *
     * @return the value of books.Author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Author
     *
     * @param author the value for books.Author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Title
     *
     * @return the value of books.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Title
     *
     * @param title the value for books.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Price
     *
     * @return the value of books.Price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Price
     *
     * @param price the value for books.Price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Publishingdate
     *
     * @return the value of books.Publishingdate
     *
     * @mbg.generated
     */
    public String getPublishingdate() {
        return publishingdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Publishingdate
     *
     * @param publishingdate the value for books.Publishingdate
     *
     * @mbg.generated
     */
    public void setPublishingdate(String publishingdate) {
        this.publishingdate = publishingdate == null ? null : publishingdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Salesamount
     *
     * @return the value of books.Salesamount
     *
     * @mbg.generated
     */
    public Integer getSalesamount() {
        return salesamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Salesamount
     *
     * @param salesamount the value for books.Salesamount
     *
     * @mbg.generated
     */
    public void setSalesamount(Integer salesamount) {
        this.salesamount = salesamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.Storenumber
     *
     * @return the value of books.Storenumber
     *
     * @mbg.generated
     */
    public Integer getStorenumber() {
        return storenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.Storenumber
     *
     * @param storenumber the value for books.Storenumber
     *
     * @mbg.generated
     */
    public void setStorenumber(Integer storenumber) {
        this.storenumber = storenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", author=").append(author);
        sb.append(", title=").append(title);
        sb.append(", price=").append(price);
        sb.append(", publishingdate=").append(publishingdate);
        sb.append(", salesamount=").append(salesamount);
        sb.append(", storenumber=").append(storenumber);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}