server:
  port: 8001



spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/druid?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource



mybatis:
  #    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#  mapper-locations: com/tom/springcloud/mapper/*.xml


eureka:
  client:
    service-url:
     defaultZone: http://127:0:0:1:${server.port}/
